Pages/AddWaterConsumption.cshtml.cs
using EcoEnergyRazorBBDD.Data;
using EcoEnergyRazorBBDD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Xml.Linq;

namespace EcoEnergyRazorBBDD.Pages
{
    public class AddWaterConsumptionModel : PageModel
    {
        [BindProperty]
        public WaterConsumptionLog? UserWaterConsumption { get; set; }

        public IActionResult OnPost()
        {
            using var context = new ApplicationDbContext();
            context.WaterConsumption.Add(UserWaterConsumption);
            context.SaveChanges();
            return RedirectToPage("WaterConsumption");
        }
    }
}

Pages/EnergeticIndicators.cshtml.cs
using CsvHelper;
using CsvHelper.Configuration;
using EcoEnergyRazorBBDD.Data;
using EcoEnergyRazorBBDD.DTOs;
using EcoEnergyRazorBBDD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;
using System.Net;

namespace EcoEnergyRazorBBDD.Pages
{
    public class EnergeticIndicatorsModel : PageModel
    {
        // Flags to indicate  records availability
        public bool FileHasRecords { get; set; }

        // Lists to store energy indicators and calculated averages
        public List<EnergyIndicator> EnergyIndicatorList { get; set; } = new List<EnergyIndicator>();
        public void OnGet()
        {
            using var context = new ApplicationDbContext();
            EnergyIndicatorList = context.EnergyIndicator.ToList();
            FileHasRecords = EnergyIndicatorList.Count > 0;
        }
        public IActionResult OnPostDeleteRecord(int id)
        {
            using var context = new ApplicationDbContext();
            EnergyIndicator simDelete = context.EnergyIndicator.Find(id)!;
            Console.WriteLine(simDelete);
            context.EnergyIndicator.Remove(simDelete);
            context.SaveChanges();
            return RedirectToPage("EnergeticIndicators");
        }
        public IActionResult OnPostUpdateRecord(int id)
        {
            return RedirectToPage("UpdateEnergyIndicators", "Indicator", new { Id = id });
        }
        public IActionResult OnPostSeed()
        {
            using var context = new ApplicationDbContext();
            var reader = new StreamReader("wwwroot/Files/indicadors_energetics_cat.csv");
            using var csv = new CsvReader(reader, CultureInfo.InvariantCulture);
            var records = csv.GetRecords<EnergyIndicatorDTO>().ToList();
            foreach (var r in records)
            {
                EnergyIndicator indicador = new EnergyIndicator
                {
                    Date = r.Date,
                    PBEE_Hydroelectric = r.PBEE_Hydroelectric,
                    PBEE_Coal = r.PBEE_Coal,
                    PBEE_NaturalGas = r.PBEE_NaturalGas,
                    PBEE_FuelOil = r.PBEE_FuelOil,
                    PBEE_CombinedCycle = r.PBEE_CombinedCycle,
                    PBEE_Nuclear = r.PBEE_Nuclear,
                    CDEEBC_GrossProduction = r.CDEEBC_GrossProduction,
                    CDEEBC_AuxConsumption = r.CDEEBC_AuxConsumption,
                    CDEEBC_NetProduction = r.CDEEBC_NetProduction,
                    CDEEBC_PumpConsumption = r.CDEEBC_PumpConsumption,
                    CDEEBC_AvailableProduction = r.CDEEBC_AvailableProduction,
                    CDEEBC_TotalNetworkSalesCentral = r.CDEEBC_TotalNetworkSalesCentral,
                    CDEEBC_ElectricExchangeBalance = r.CDEEBC_ElectricExchangeBalance,
                    CDEEBC_ElectricDemand = r.CDEEBC_ElectricDemand,
                    CDEEBC_TotalRegulatedMarket = r.CDEEBC_TotalRegulatedMarket,
                    CDEEBC_TotalFreeMarket = r.CDEEBC_TotalFreeMarket,
                    FEE_Industry = r.FEE_Industry,
                    FEE_Tertiary = r.FEE_Tertiary,
                    FEE_Domestic = r.FEE_Domestic,
                    FEE_Primary = r.FEE_Primary,
                    FEE_Energetic = r.FEE_Energetic,
                    FEEI_PublicWorksConsumption = r.FEEI_PublicWorksConsumption,
                    FEEI_IronSteelFoundry = r.FEEI_IronSteelFoundry,
                    FEEI_Metallurgy = r.FEEI_Metallurgy,
                    FEEI_GlassIndustry = r.FEEI_GlassIndustry,
                    FEEI_CementLimeGypsum = r.FEEI_CementLimeGypsum,
                    FEEI_OtherConstructionMaterials = r.FEEI_OtherConstructionMaterials,
                    FEEI_ChemicalPetrochemical = r.FEEI_ChemicalPetrochemical,
                    FEEI_TransportMediumConstruction = r.FEEI_TransportMediumConstruction,
                    FEEI_OtherMetalTransformation = r.FEEI_OtherMetalTransformation,
                    FEEI_FoodBeverageTobacco = r.FEEI_FoodBeverageTobacco,
                    FEEI_TextileClothingLeatherFootwear = r.FEEI_TextileClothingLeatherFootwear,
                    FEEI_PulpPaperCardboard = r.FEEI_PulpPaperCardboard,
                    FEEI_OtherIndustries = r.FEEI_OtherIndustries,
                    DGGN_FrontierPointEnagas = r.DGGN_FrontierPointEnagas,
                    DGGN_LNGDistributionSupply = r.DGGN_LNGDistributionSupply,
                    DGGN_ThermalPowerPlantGNCConsumption = r.DGGN_ThermalPowerPlantGNCConsumption,
                    CCAC_AutoGasoline = r.CCAC_AutoGasoline,
                    CCAC_AutoDieselA = r.CCAC_AutoDieselA
                };
                context.EnergyIndicator.Add(indicador);
                context.SaveChanges();
            }
            return RedirectToPage("EnergeticIndicators");
        }
        public IActionResult OnPostDeleteAll()
        {
            using var context = new ApplicationDbContext();
            context.EnergyIndicator.RemoveRange(context.EnergyIndicator);
            context.SaveChanges();
            return RedirectToPage("EnergeticIndicators");
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EcoEnergyRazorBBDD.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EcoEnergyRazorBBDD.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/InsertEnergyIndicator.cshtml.cs
using EcoEnergyRazorBBDD.Data;
using EcoEnergyRazorBBDD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace EcoEnergyRazorBBDD.Pages
{
    // PageModel for inserting a new energy indicator
    public class InsertEnergyIndicatorModel : PageModel
    {
        [BindProperty]
        public EnergyIndicator? EnergyIndicator { get; set; }
        public IActionResult OnPost()
        {
            const double defaultValue = 0;

            // Create a new EnergyIndicator object with specified and default values
            EnergyIndicator indicator = new EnergyIndicator
            {
                Date = EnergyIndicator!.Date,
                PBEE_Hydroelectric = defaultValue,
                PBEE_Coal = defaultValue,
                PBEE_NaturalGas = defaultValue,
                PBEE_FuelOil = defaultValue,
                PBEE_CombinedCycle = defaultValue,
                PBEE_Nuclear = defaultValue,
                CDEEBC_GrossProduction = defaultValue,
                CDEEBC_AuxConsumption = defaultValue,
                CDEEBC_NetProduction = EnergyIndicator.CDEEBC_NetProduction,
                CDEEBC_PumpConsumption = defaultValue,
                CDEEBC_AvailableProduction = EnergyIndicator.CDEEBC_AvailableProduction,
                CDEEBC_TotalNetworkSalesCentral = defaultValue,
                CDEEBC_ElectricExchangeBalance = defaultValue,
                CDEEBC_ElectricDemand = EnergyIndicator.CDEEBC_ElectricDemand,
                CDEEBC_TotalRegulatedMarket = defaultValue,
                CDEEBC_TotalFreeMarket = defaultValue,
                FEE_Industry = defaultValue,
                FEE_Tertiary = defaultValue,
                FEE_Domestic = defaultValue,
                FEE_Primary = defaultValue,
                FEE_Energetic = defaultValue,
                FEEI_PublicWorksConsumption = defaultValue,
                FEEI_IronSteelFoundry = defaultValue,
                FEEI_Metallurgy = defaultValue,
                FEEI_GlassIndustry = defaultValue,
                FEEI_CementLimeGypsum = defaultValue,
                FEEI_OtherConstructionMaterials = defaultValue,
                FEEI_ChemicalPetrochemical = defaultValue,
                FEEI_TransportMediumConstruction = defaultValue,
                FEEI_OtherMetalTransformation = defaultValue,
                FEEI_FoodBeverageTobacco = defaultValue,
                FEEI_TextileClothingLeatherFootwear = defaultValue,
                FEEI_PulpPaperCardboard = defaultValue,
                FEEI_OtherIndustries = defaultValue,
                DGGN_FrontierPointEnagas = defaultValue,
                DGGN_LNGDistributionSupply = defaultValue,
                DGGN_ThermalPowerPlantGNCConsumption = defaultValue,
                CCAC_AutoGasoline = EnergyIndicator.CCAC_AutoGasoline,
                CCAC_AutoDieselA = defaultValue
            };
            using var context = new ApplicationDbContext();
            context.EnergyIndicator.Add(indicator);
            context.SaveChanges();
            return RedirectToPage("EnergeticIndicators");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EcoEnergyRazorBBDD.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/SimCreator.cshtml.cs
using CsvHelper;
using CsvHelper.Configuration;
using EcoEnergyRazorBBDD.Data;
using EcoEnergyRazorBBDD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;
using static EcoEnergyRazorBBDD.Models.EnergySystem;

namespace EcoEnergyRazorBBDD.Pages
{
    // PageModel for creating energy simulations
    public class SimCreatorModel : PageModel
    {
        [BindProperty]
        public EnergySystem? EnergySystem { get; set; }
        [BindProperty]
        public SolarSystem? SolarSystem { get; set; }
        [BindProperty]
        public HydroElectricSystem? HydroElectricSystem { get; set; }
        [BindProperty]
        public EolicSystem? EolicSystem { get; set; }
        [BindProperty]
        public EnergyType? Type { get; set; }

        public IActionResult OnPost()
        {

            // Validate inputs based on energy type
            switch (Type)
            {
                case EnergyType.SolarEnergy:
                    if (SolarSystem != null && SolarSystem.SunHours < 1)
                    {
                        ModelState.AddModelError("SolarSystem.SunHours", "The amount of hours of sun has to be greater than 1h");
                        return Page();
                    }
                    break;
                case EnergyType.EolicEnergy:
                    if (EolicSystem != null && EolicSystem.WindVelocity < 5)
                    {
                        ModelState.AddModelError("EolicSystem.WindVelocity", "The speed of the wind has to be greater than 5km/h");
                        return Page();
                    }
                    break;
                case EnergyType.HydroElectricEnergy:
                    if (HydroElectricSystem != null && HydroElectricSystem.WaterLevel < 20)
                    {
                        ModelState.AddModelError("HydroElectricSystem", "The water level has to be greater than 20m");
                        return Page();
                    }
                    break;
            }

            // Save the appropriate simulation record based on the energy type
            using var context = new ApplicationDbContext();
            switch (Type)
            {
                case EnergyType.SolarEnergy:
                    SolarSystem simulationSolar = new SolarSystem(SolarSystem!.SunHours, EnergySystem!.Price, EnergySystem.Ratio, EnergySystem.Cost);
                    context.Simulations.Add(simulationSolar);
                    context.SaveChanges();
                    break;
                case EnergyType.EolicEnergy:
                    EolicSystem simulationEolic = new EolicSystem(EolicSystem!.WindVelocity, EnergySystem!.Price, EnergySystem.Ratio, EnergySystem.Cost);
                    context.Simulations.Add(simulationEolic);
                    context.SaveChanges();
                    break;
                case EnergyType.HydroElectricEnergy:
                    HydroElectricSystem simulationWater = new HydroElectricSystem(HydroElectricSystem!.WaterLevel, EnergySystem!.Price, EnergySystem.Ratio, EnergySystem.Cost);
                    context.Simulations.Add(simulationWater);
                    context.SaveChanges();
                    break;
            }
            return RedirectToPage("Simulations");
        }
    }
}

Pages/Simulations.cshtml.cs
using EcoEnergyRazorBBDD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CsvHelper;
using System.Globalization;
using CsvHelper.Configuration;
using EcoEnergyRazorBBDD.Data;

namespace EcoEnergyRazorBBDD.Pages
{
    // PageModel for displaying saved energy simulations
    public class SimulationsModel : PageModel
    {
        public List<EnergySystem> Simulations { get; set; } = new List<EnergySystem>();
        public bool FileHasRecords { get; set; }

        public void OnGet()
        {
            using var context = new ApplicationDbContext();
            Simulations = context.Simulations.ToList();
            FileHasRecords = Simulations.Count > 0;
        }
        public IActionResult OnPostDeleteRecord(int id)
        {
            using var context = new ApplicationDbContext();
            EnergySystem simDelete = context.Simulations.Find(id)!;
            Console.WriteLine(simDelete);
            context.Simulations.Remove(simDelete);
            context.SaveChanges();
            return RedirectToPage("Simulations");
        }
        public IActionResult OnPostUpdateRecord(int id)
        {
            return RedirectToPage("UpdateSimulation", "Simulation", new { Id = id });
        }
    }
}

Pages/UpdateEnergyIndicators.cshtml.cs
using EcoEnergyRazorBBDD.Data;
using EcoEnergyRazorBBDD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EcoEnergyRazorBBDD.Pages
{
    public class UpdateEnergyIndicatorsModel : PageModel
    {
        [BindProperty]
        public EnergyIndicator EnergyIndicator { get; set; }
        public void OnGetIndicator(int id)
        {
            using var context = new ApplicationDbContext();
            EnergyIndicator = context.EnergyIndicator.Find(id);
        }
        public IActionResult OnPost()
        {
            using var context = new ApplicationDbContext();
            EnergyIndicator indicatorToUpdate = context.EnergyIndicator.Find(EnergyIndicator.Id);
            indicatorToUpdate.Date = EnergyIndicator.Date;
            indicatorToUpdate.CDEEBC_NetProduction = EnergyIndicator.CDEEBC_NetProduction;
            indicatorToUpdate.CCAC_AutoGasoline = EnergyIndicator.CCAC_AutoGasoline;
            indicatorToUpdate.CDEEBC_ElectricDemand = EnergyIndicator.CDEEBC_ElectricDemand;
            indicatorToUpdate.CDEEBC_AvailableProduction = EnergyIndicator.CDEEBC_AvailableProduction;
            context.SaveChanges();
            return RedirectToPage("EnergeticIndicators");
        }
    }
}

Pages/UpdateSimulation.cshtml.cs
using EcoEnergyRazorBBDD.Data;
using EcoEnergyRazorBBDD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EcoEnergyRazorBBDD.Pages
{
    public class UpdateSimulationModel : PageModel
    {
        [BindProperty]
        public EnergySystem Simulation { get; set; }
        public void OnGetSimulation(int id)
        {
            using var context = new ApplicationDbContext();
            Simulation = context.Simulations.Find(id);
        }
        public IActionResult OnPost()
        {
            using var context = new ApplicationDbContext();
            var simulationToUpdate = context.Simulations.Find(Simulation.Id);
            simulationToUpdate.Type = Simulation.Type;
            simulationToUpdate.Ratio = Simulation.Ratio;
            simulationToUpdate.Energy = Simulation.Energy;
            simulationToUpdate.Date = Simulation.Date;
            simulationToUpdate.Price = Simulation.Price;
            simulationToUpdate.Cost = Simulation.Cost;
            simulationToUpdate.TotalCost = Simulation.CalculateTotalCost();
            simulationToUpdate.TotalPrice = Simulation.CalculateTotalPrice();
            context.SaveChanges();
            return RedirectToPage("Simulations");
        }
    }
}

Pages/EnergeticIndicators.cshtml
@page
@model EcoEnergyRazorBBDD.Pages.EnergeticIndicatorsModel
@{
	ViewData["title"] = "Energetic Indicators";
}
<div>
    <h2>Detailed info</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>PBEE_Hydroelectric</th>
                <th>PBEE_Coal</th>
                <th>PBEE_NaturalGas</th>
                <th>PBEE_FuelOil</th>
                <th>PBEE_CombinedCycle</th>
                <th>PBEE_Nuclear</th>
                <th>CDEEBC_GrossProduction</th>
                <th>CDEEBC_AuxConsumption</th>
                <th>CDEEBC_NetProduction</th>
                <th>CDEEBC_PumpConsumption</th>
                <th>CDEEBC_AvailableProduction</th>
                <th>CDEEBC_TotalNetworkSalesCentral</th>
                <th>CDEEBC_ElectricExchangeBalance</th>
                <th>CDEEBC_ElectricDemand</th>
                <th>CDEEBC_TotalRegulatedMarket</th>
                <th>CDEEBC_TotalFreeMarket</th>
                <th>FEE_Industry</th>
                <th>FEE_Tertiary</th>
                <th>FEE_Domestic</th>
                <th>FEE_Primary</th>
                <th>FEE_Energetic</th>
                <th>FEEI_PublicWorksConsumption</th>
                <th>FEEI_IronSteelFoundry</th>
                <th>FEEI_Metallurgy</th>
                <th>FEEI_GlassIndustry</th>
                <th>FEEI_CementLimeGypsum</th>
                <th>FEEI_OtherConstructionMaterials</th>
                <th>FEEI_ChemicalPetrochemical</th>
                <th>FEEI_TransportMediumConstruction</th>
                <th>FEEI_OtherMetalTransformation</th>
                <th>FEEI_FoodBeverageTobacco</th>
                <th>FEEI_TextileClothingLeatherFootwear</th>
                <th>FEEI_PulpPaperCardboard</th>
                <th>FEEI_OtherIndustries</th>
                <th>DGGN_FrontierPointEnagas</th>
                <th>DGGN_LNGDistributionSupply</th>
                <th>DGGN_ThermalPowerPlantGNCConsumption</th>
                <th>CCAC_AutoGasoline</th>
                <th>CCAC_AutoDieselA</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.FileHasRecords)
			{@foreach (var indicator in Model.EnergyIndicatorList)
				{
            <tr>
                <td>@indicator.Date</td>
                <td>@indicator.PBEE_Hydroelectric</td>
                <td>@indicator.PBEE_Coal</td>
                <td>@indicator.PBEE_NaturalGas</td>
                <td>@indicator.PBEE_FuelOil</td>
                <td>@indicator.PBEE_CombinedCycle</td>
                <td>@indicator.PBEE_Nuclear</td>
                <td>@indicator.CDEEBC_GrossProduction</td>
                <td>@indicator.CDEEBC_AuxConsumption</td>
                <td>@indicator.CDEEBC_NetProduction</td>
                <td>@indicator.CDEEBC_PumpConsumption</td>
                <td>@indicator.CDEEBC_AvailableProduction</td>
                <td>@indicator.CDEEBC_TotalNetworkSalesCentral</td>
                <td>@indicator.CDEEBC_ElectricExchangeBalance</td>
                <td>@indicator.CDEEBC_ElectricDemand</td>
                <td>@indicator.CDEEBC_TotalRegulatedMarket</td>
                <td>@indicator.CDEEBC_TotalFreeMarket</td>
                <td>@indicator.FEE_Industry</td>
                <td>@indicator.FEE_Tertiary</td>
                <td>@indicator.FEE_Domestic</td>
                <td>@indicator.FEE_Primary</td>
                <td>@indicator.FEE_Energetic</td>
                <td>@indicator.FEEI_PublicWorksConsumption</td>
                <td>@indicator.FEEI_IronSteelFoundry</td>
                <td>@indicator.FEEI_Metallurgy</td>
                <td>@indicator.FEEI_GlassIndustry</td>
                <td>@indicator.FEEI_CementLimeGypsum</td>
                <td>@indicator.FEEI_OtherConstructionMaterials</td>
                <td>@indicator.FEEI_ChemicalPetrochemical</td>
                <td>@indicator.FEEI_TransportMediumConstruction</td>
                <td>@indicator.FEEI_OtherMetalTransformation</td>
                <td>@indicator.FEEI_FoodBeverageTobacco</td>
                <td>@indicator.FEEI_TextileClothingLeatherFootwear</td>
                <td>@indicator.FEEI_PulpPaperCardboard</td>
                <td>@indicator.FEEI_OtherIndustries</td>
                <td>@indicator.DGGN_FrontierPointEnagas</td>
                <td>@indicator.DGGN_LNGDistributionSupply</td>
                <td>@indicator.DGGN_ThermalPowerPlantGNCConsumption</td>
                <td>@indicator.CCAC_AutoGasoline</td>
                <td>@indicator.CCAC_AutoDieselA</td>
                <td><form method="post" aps-handler="DeleteRecord"><button type="submit" asp-page-handler="DeleteRecord" asp-route-id="@indicator.Id">X</button></form></td>
                <td><form method="post" aps-handler="UpdateRecord"><button type="submit" asp-page-handler="UpdateRecord" asp-route-id="@indicator.Id">Edit</button></form></td>
            </tr>
				} }
			else
			{
                <tr><td>There are no energy indicators</td></tr>
			}
        </tbody>
    </table>
</div>
<div>
    <form method="post">
        <a asp-page="/InsertEnergyIndicator" class="btn btn-primary">Add Energetic Indicator</a>
        <button type="submit" asp-page-handler="Seed" class="btn btn-primary">Import CSV records</button>
        <button type="submit" asp-page-handler="DeleteAll" class="btn btn-primary">Delete all records</button>
    </form>
</div>
<p>Register Count: @Model.EnergyIndicatorList.Count</p>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <img src="~/Images/image.png" alt="" class="index_img" />
    <p class="font_title">EcoEnergy Solutions</p>
    <p class="font_subtitle">For a brighter future</p>
</div>

Pages/Simulations.cshtml
@page
@model EcoEnergyRazorBBDD.Pages.SimulationsModel
@{
	ViewData["Title"] = "Simulations list";
}
<div class="text-center">
	<h2>Simulation List</h2>
	<table class="table">
		<thead>
			<tr>
				<th>Type</th>
				<th>Date</th>
				<th>Ratio</th>
				<th>Energy</th>
				<th>Cost</th>
				<th>Total Cost</th>
				<th>Price</th>
				<th>Total Price</th>
			</tr>
		</thead>
		<tbody>
			@if (Model.FileHasRecords)
			{
				@foreach (var simulation in Model.Simulations)
				{
					<tr>
						<td>@simulation.GetEnergyType()</td>
						<td>@simulation.GetDate()</td>
						<td>@simulation.Ratio</td>
						<td>@simulation.Energy</td>
						<td>@simulation.Cost</td>
						<td>@simulation.TotalCost</td>
						<td>@simulation.Price</td>
						<td>@simulation.TotalPrice</td>
						<td><form method="post" aps-handler="DeleteRecord"><button type="submit" asp-page-handler="DeleteRecord" asp-route-id="@simulation.Id">X</button></form></td>
						<td><form method="post" aps-handler="UpdateRecord"><button type="submit" asp-page-handler="UpdateRecord" asp-route-id="@simulation.Id">Edit</button></form></td>
					</tr>
				}
			}
			else
			{
				<tr><td>No existeix ninguna simulació</td></tr>
			}
			
		</tbody>
</table>
<a class="btn btn-primary" asp-page="/SimCreator">Create new simulation</a>
</div>

Pages/WaterConsumption.cshtml
@page
@model EcoEnergyRazorBBDD.Pages.WaterConsumptionModel
@{
	ViewData["title"] = "Water consumption";
}
<div>
	<h2>Water Consumption detailed info</h2>
	<table class="table">
		<thead>
			<tr>
				<th>Year</th>
				<th>Region Code</th>
				<th>Region Name</th>
				<th>Population</th>
				<th>Domestic Grid</th>
				<th>Economic activities & own sources</th>
				<th>Total</th>
				<th>Domestic consumption per capita</th>
			</tr>
		</thead>
		<tbody>
			@if (Model.FileHasRecords)
			{
				@foreach (var simulation in Model.WaterConsumptionList)
				{
					<tr>
						<td>@simulation.Year</td>
						<td>@simulation.RegionID</td>
						<td>@simulation.RegionName</td>
						<td>@simulation.Population</td>
						<td>@simulation.DomesticNET</td>
						<td>@simulation.EconomicActivities</td>
						<td>@simulation.Total</td>
						<td>@simulation.DomesticConsumption</td>
						<td><form method="post" aps-handler="DeleteRecord"><button type="submit" asp-page-handler="DeleteRecord" asp-route-id="@simulation.Id">X</button></form></td>
						<td><form method="post" aps-handler="UpdateRecord"><button type="submit" asp-page-handler="UpdateRecord" asp-route-id="@simulation.Id">Edit</button></form></td>
					</tr>
				}
			}
			else
			{
				<tr><td>There aren't any cosumptions</td></tr>
			}
		</tbody>
	</table>
</div>
<div>
	<form method="post">
		<a asp-page="/AddWaterConsumption" class="btn btn-primary">Add Water Consumption</a>
		<button type="submit" asp-page-handler="Seed" class="btn btn-primary">Import CSV records</button>
		<button type="submit" asp-page-handler="DeleteAll" class="btn btn-primary">Delete all records</button>
	</form>
</div>